### ISSUE TITLE
Loading a multi-LoD file into different layers not working

### ISSUE THREAD

**Issue by jliempt** [cityjson/cityjson-qgis-plugin#34]
I have been trying to load a file from the new 3D BAG (tile #5910 to be specific) and despite setting `Load LoD:` to `As Layers` I only get one layer, whereas there should be three.

QGIS version: 3.16.4-Hannover

**Comment by Geogoeroe** [comment]
Same here. I've had a look at the way the set parameter (lod_as = 'LAYERS') is being used in the code, but I only find it in this snippet: 

        if lod_as in ['ATTRIBUTES', 'LAYERS']:
            self.fields_builder = LodFieldsDecorator(self.fields_builder)
            self.feature_builder = LodFeatureDecorator(self.feature_builder,
                                                       self.geometry_reader)

So my guess is that Load LoD just gives an extra field for the LoD when attributes or layers are picked. And no extra field when none is picked.
The expected behaviour would be that for the different values of LoD a diferent layer would be created when "Layers" is picked. I do not recognize adding of different layers somewhere...

**Comment by liberostelios** [comment]
This issue is now fixed in version [0.7.2](https://github.com/cityjson/cityjson-qgis-plugin/releases/tag/v0.7.2).
