### ISSUE TITLE
CityJSON v1.1 not supported

### ISSUE THREAD

**Issue by hugoledoux** [cityjson/cityjson-qgis-plugin#45]
eg with this: https://3d.bk.tudelft.nl/opendata/cityjson/3dcities/v1.1/DenHaag_01.city.json

**Comment by liberostelios** [comment]
I believe this should be fixed now.

Based on [this](https://www.cityjson.org/dev/upgrade11/) list:
1. doesn't change much for parsing
2. same
3. was treating it as string anyway
4. fixed in dc8a538
5. keep parsing all metadata as they come, but now also merge any metadata from the extension (fixed in 3f1b754)
6. not really affected, as `"children"` was expected anyway (wrong before, but convenient now)
7. unaffected (we are city object agnostic)
8. same
9. same
10. fixed already with #43
11. probably that urgent so I am extracting this as its own issue (#46) for the future
